### ISSUE TITLE
include installed package versions

### ISSUE THREAD

**Issue by merouanezouaid** [merouanezouaid/pwp#1]
the way i see it to add a flag (for example `--v` for version) to the pwp install command. 

when this flag is used, pwp would add the package name along with the installed version to the requirements.txt file. 

if the flag is not used, pwp would behave as it currently does, adding only the package name.

**Comment by AnasImloul** [comment]
Hey, I have made some changes for the version flag. I didn't notice that you had already assigned yourself to it. I hope there's no duplication of work.

**Comment by merouanezouaid** [comment]
no problem @AnasImloul! 

you're 100% good :)
